# -*- coding: utf-8 -*-
"""Análisis_Portafolios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHRI3VCCTIOc3M4eLd18hLDRVqrlBv_n
"""

!pip install streamlit

#Importación las librerías

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

"""En este proyecto se analiza un portafolio de inversión aplicando la teoría moderna de portafolios de Markowitz.
Se simulan tres escenarios (conservador, moderado y agresivo) para observar cómo varían el riesgo, el rendimiento y la composición de activos.
Los datos se obtienen directamente desde Yahoo Finance, y los activos seleccionados son empresas tecnológicas del mercado.
"""

st.title ("💼 Simulación de Portafolios de Inversión")

st.write("Analiza diferentes escenarios (conservador, moderado, agresivo) con datos reales del mercado 📈")

# Lista de tickers

lista_tickers = ['AAPL', 'MSFT', 'META']

print("Activos disponibles:", lista_tickers)

# Selector interactivo

ticker=st.selectbox("Seleccione un ticker", lista_tickers)

# Botón para descargar los datos

if st.button("Descargar"):
  # Descarga de precios del último mes
    data = yf.download(ticker, period="1mo")
    st.subheader("📈 Datos descargados")
    st.dataframe(data.tail())

# Descarga de datos

data = yf.download(tickers, start='2020-01-01', end='2023-12-31')['Close']

print("✅ Datos descargados correctamente")

# Visualizamos las primeras filas para verificar la estructura de los datos

data.head()

# Visualización de precios

data.plot(figsize=(10,5))
plt.title("Evolución histórica de precios ajustados")
plt.xlabel("Fecha")
plt.ylabel("Precio (USD)")
plt.grid(True)
plt.show()

# Cálculo de rendimientos y estadísticas básicas

# Rendimientos diarios

returns = data.pct_change().dropna()

print("📈 Rendimientos esperados (anualizados):")
display(mean_returns)

# Rendimientos y covarianza anualizados

mean_returns = returns.mean() * 252
cov_matrix = returns.cov() * 252
volatility = returns.std() * np.sqrt(252)

print("\n📊 Matriz de covarianza (anualizada):")
display(cov_matrix)

# Estadísticas generales
display(returns.describe().T)

#Correclaciones entre activos

corr_matrix = returns.corr()
display(corr_matrix)

plt.figure(figsize=(6,5))
plt.imshow(corr_matrix, cmap='coolwarm', interpolation='nearest')
plt.colorbar(label="Correlación")
plt.xticks(range(len(corr_matrix)), corr_matrix.columns, rotation=45)
plt.yticks(range(len(corr_matrix)), corr_matrix.columns)
plt.title("Matriz de correlación entre activos")
plt.show()

# Selección de escenario

st.subheader("Escenario de inversión")
escenario = st.selectbox("Seleccione el tipo de portafolio", ["Conservador", "Moderado", "Agresivo"])

# Simulación de escenarios

# Definición de escenarios
escenarios = {
    "Conservador": np.array([0.6, 0.3, 0.1]),
    "Moderado":    np.array([0.4, 0.4, 0.2]),
    "Agresivo":    np.array([0.2, 0.3, 0.5])
}

resultados = []

print("🏦 Resultados de los escenarios:\n")

if escenario == "Conservador":
    weights = np.array([0.6, 0.3, 0.1])
elif escenario == "Moderado":
    weights = np.array([0.4, 0.4, 0.2])
else:  # Agresivo
    weights = np.array([0.2, 0.3, 0.5])

# Normalización de pesos

weights = weights / np.sum(weights)

# Cálculo del portafolio

port_return = np.dot(weights, mean_returns)
port_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
sharpe_ratio = port_return / port_volatility

# Resultados

st.subheader("📊 Resultados del escenario seleccionado")
st.write("**Pesos del portafolio:**", dict(zip(lista_tickers, weights.round(2))))
st.write(f"**Rendimiento esperado:** {port_return:.2%}")
st.write(f"**Volatilidad esperada:** {port_volatility:.2%}")
st.write(f"**Ratio de Sharpe:** {sharpe_ratio:.2f}")

# Convertir a DataFrame para análisis

df_resultados = pd.DataFrame(resultados, columns=["Escenario", "Rendimiento", "Riesgo", "Sharpe"])
display(df_resultados)

# Visualización comparativa de los escenarios

plt.figure(figsize=(7,5))
plt.scatter(df_resultados["Riesgo"], df_resultados["Rendimiento"], s=200)

for i in range(len(df_resultados)):
    plt.text(df_resultados["Riesgo"][i]+0.0005,
             df_resultados["Rendimiento"][i],
             df_resultados["Escenario"][i],
             fontsize=12)

plt.title("Comparativo de escenarios de inversión")
plt.xlabel("Riesgo (Volatilidad)")
plt.ylabel("Rendimiento esperado")
plt.grid(True)
plt.show()

# Distribución de pesos por escenario

fig, axs = plt.subplots(1, 3, figsize=(12,4))

for i, (nombre, w) in enumerate(escenarios.items()):
    w = w[:len(returns.columns)]
    w = w / np.sum(w)
    axs[i].pie(w, labels=returns.columns, autopct='%1.1f%%', startangle=90)
    axs[i].set_title(nombre)

plt.suptitle("Distribución de pesos por escenario de inversión")
plt.show()

"""**Conclusiones**

El escenario conservador muestra menor volatilidad y menor rendimiento esperado.

El escenario agresivo ofrece mayor retorno, pero con un incremento notable del riesgo.

El ratio de Sharpe evidencia que el escenario moderado puede ofrecer la mejor relación riesgo/retorno.

En general, la simulación valida la teoría de Markowitz: la diversificación permite ajustar el riesgo y rendimiento según el perfil del inversionista.
"""