# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztIPfXqXvqCtsCpohm_Mmx5c5SIFecZc
"""

!pip install streamlit

#Importamos las librerías

import streamlit as st
import pandas as pd
import yfinance as yf

st.title ("Mi Primera Aplicación en Streamlit")

# Lista de tickers inicial

lista_tickers = ['AAPL', 'MSFT', 'NVDA']

# Selector

ticker=st.selectbox("Elija un ticker", lista_tickers)

# Boton

if st.button("Descargar"):
  data=yf.download(ticker, period="1mo")
  st.dataframe(data)