# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztIPfXqXvqCtsCpohm_Mmx5c5SIFecZc
"""

#!pip install streamlit

# Importamos las librerías
import streamlit as st
import pandas as pd

st.title ("Mi Primera Aplicación en Streamlit")
