# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztIPfXqXvqCtsCpohm_Mmx5c5SIFecZc
"""

#Importamos las librerías

import streamlit as st
import pandas as pd

!pip install streamlit

st.title ("Mi Primera Aplicación en Streamlit")